# Generated by Django 4.1.2 on 2022-12-09 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userFunctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employessActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(default='Fazer pedido...', max_length=500)),
                ('prazo_maximo', models.DateField()),
                ('empregado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='compTeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Equipe/Organização', max_length=255)),
                ('email_profissional', models.EmailField(max_length=254)),
                ('imagem_do_time', models.ImageField(blank=True, default='company.png', null=True, upload_to='companys/')),
                ('horario_de_atividade', models.TimeField()),
                ('atividades', models.ManyToManyField(to='companyTeam.employessactivities')),
                ('integrantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userFunctions.profile')),
            ],
        ),
    ]
