# Generated by Django 4.1.2 on 2022-12-04 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userFunctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compTeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Equipe/Organização', max_length=255)),
                ('email_profissional', models.EmailField(max_length=254)),
                ('imagem_do_time', models.ImageField(blank=True, default='company.png', null=True, upload_to='companys/')),
                ('horario_de_atividade', models.DateTimeField(blank=True)),
                ('integrantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userFunctions.profile')),
            ],
        ),
    ]
