# Generated by Django 4.1.2 on 2022-12-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyTeam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteammodel',
            name='horario_de_atividade',
            field=models.TimeField(),
        ),
    ]
