# Generated by Django 4.1.2 on 2022-12-05 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companyTeam', '0002_alter_compteammodel_horario_de_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='employessActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.TextField()),
                ('prazo_final', models.DateTimeField(auto_now_add=True)),
                ('integrante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
