# Generated by Django 4.1.2 on 2022-12-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyTeam', '0003_employessactivities'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteammodel',
            name='atividades',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyTeam.employessactivities'),
        ),
        migrations.AlterField(
            model_name='employessactivities',
            name='atividade',
            field=models.TextField(default='Fazer pedido...'),
        ),
        migrations.AlterField(
            model_name='employessactivities',
            name='prazo_final',
            field=models.DateTimeField(),
        ),
    ]
