# Generated by Django 4.1.2 on 2022-11-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(help_text='Ex: 11999999999', max_length=11)),
                ('endereco', models.TextField(help_text='Rua,numero,cep,complemento etc..')),
            ],
        ),
    ]
